version: 2
updates:
  - package-ecosystem: pip
    directories:
      - /
      - /docs
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Oslo
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Oslo
    groups:
      pre-commit-hooks:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Oslo
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
